### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [appropriate/docker-jetty#74] opened 2017-09-26 11:41 UTC
Hi, I'm looking to enable docker containers for packages like jetty for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

Would like to know how a multi-arch image for this can be initiated? The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, however this repo isnt an official image yet. Would the first step be to make this an official image or are there any other ways the dockerhub jetty image can be enabled for ppc64le?

**Comment by tianon** [comment] 2017-09-26 14:15
This is a duplicate of #68 (which has a bit of discussion about this topic already) :+1:

**Comment by md5** [comment] 2017-09-27 03:10
Thanks @tianon 

@vaibhavsood Please discuss on #68

**Closed as completed by md5** 2017-09-27 03:10 UTC
